services:
  - type: web
    name: autopic
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOGETHER_API_KEY
        sync: false
      - key: TOGETHER_API_URL
        value: https://api.together.xyz
      - key: REDIS_URL
        sync: false
      - key: REDIS_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW
        value: 60000
      - key: RATE_LIMIT_MAX
        value: 10
      - key: IMAGE_RATE_LIMIT_MAX
        value: 5
    healthCheckPath: /api/health 